# Generated by Django 6.1.1 on 2026-09-05 15:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('key', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('short_label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('is_external_api', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_id', models.SlugField(max_length=150, unique=True)),
                ('standard_name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('who_for', models.TextField(blank=True)),
                ('typical_learner', models.TextField(blank=True)),
                ('typical_employer', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('max_funding', models.CharField(blank=True, max_length=255)),
                ('has_landing_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('trading_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('ukprn', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ofsted_status', models.CharField(blank=True, default='Not Publicly Available', max_length=255)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('delivery_model', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('strengths', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('weaknesses', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('best_for', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('logo_url', models.URLField(blank=True)),
                ('data_last_updated', models.DateField(blank=True, null=True)),
                ('company_type', models.CharField(choices=[('apprenticeship_provider', 'Apprenticeship provider'), ('college', 'College'), ('training_provider', 'Training provider'), ('employer', 'Employer'), ('university', 'University')], default='training_provider', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('merged', 'Merged')], default='active', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(default='Active', max_length=50)),
                ('evidence_source', models.CharField(blank=True, default='Register of Apprenticeship Training Providers', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.standard')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='standards',
            field=models.ManyToManyField(related_name='companies', through='catalog.CompanyStandard', to='catalog.standard'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent')], default='primary', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('standards', models.ManyToManyField(blank=True, related_name='categories', to='catalog.standard')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StandardFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.standard')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reviewsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'source'), name='unique_company_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='companystandard',
            constraint=models.UniqueConstraint(fields=('company', 'standard'), name='unique_company_standard'),
        ),
    ]
