/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          background: {
            50: "oklch(var(--background-50) / <alpha-value>)",
            100: "oklch(var(--background-100) / <alpha-value>)",
            200: "oklch(var(--background-200) / <alpha-value>)",
            300: "oklch(var(--background-300) / <alpha-value>)",
            400: "oklch(var(--background-400) / <alpha-value>)",
            500: "oklch(var(--background-500) / <alpha-value>)",
            600: "oklch(var(--background-600) / <alpha-value>)",
            700: "oklch(var(--background-700) / <alpha-value>)",
            800: "oklch(var(--background-800) / <alpha-value>)",
            900: "oklch(var(--background-900) / <alpha-value>)",
            950: "oklch(var(--background-950) / <alpha-value>)",
          },
          primary: {
            50: "oklch(var(--primary-50) / <alpha-value>)",
            100: "oklch(var(--primary-100) / <alpha-value>)",
            200: "oklch(var(--primary-200) / <alpha-value>)",
            300: "oklch(var(--primary-300) / <alpha-value>)",
            400: "oklch(var(--primary-400) / <alpha-value>)",
            500: "oklch(var(--primary-500) / <alpha-value>)",
            600: "oklch(var(--primary-600) / <alpha-value>)",
            700: "oklch(var(--primary-700) / <alpha-value>)",
            800: "oklch(var(--primary-800) / <alpha-value>)",
            900: "oklch(var(--primary-900) / <alpha-value>)",
            950: "oklch(var(--primary-950) / <alpha-value>)",
          },
          accent: {
            50: "oklch(var(--accent-50) / <alpha-value>)",
            100: "oklch(var(--accent-100) / <alpha-value>)",
            200: "oklch(var(--accent-200) / <alpha-value>)",
            300: "oklch(var(--accent-300) / <alpha-value>)",
            400: "oklch(var(--accent-400) / <alpha-value>)",
            500: "oklch(var(--accent-500) / <alpha-value>)",
            600: "oklch(var(--accent-600) / <alpha-value>)",
            700: "oklch(var(--accent-700) / <alpha-value>)",
            800: "oklch(var(--accent-800) / <alpha-value>)",
            900: "oklch(var(--accent-900) / <alpha-value>)",
            950: "oklch(var(--accent-950) / <alpha-value>)",
          },
          secondary: {
            50: "oklch(var(--secondary-50) / <alpha-value>)",
            100: "oklch(var(--secondary-100) / <alpha-value>)",
            200: "oklch(var(--secondary-200) / <alpha-value>)",
            300: "oklch(var(--secondary-300) / <alpha-value>)",
            400: "oklch(var(--secondary-400) / <alpha-value>)",
            500: "oklch(var(--secondary-500) / <alpha-value>)",
            600: "oklch(var(--secondary-600) / <alpha-value>)",
            700: "oklch(var(--secondary-700) / <alpha-value>)",
            800: "oklch(var(--secondary-800) / <alpha-value>)",
            900: "oklch(var(--secondary-900) / <alpha-value>)",
            950: "oklch(var(--secondary-950) / <alpha-value>)",
          },
          foreground: {
            50: "oklch(var(--foreground-50) / <alpha-value>)",
            100: "oklch(var(--foreground-100) / <alpha-value>)",
            200: "oklch(var(--foreground-200) / <alpha-value>)",
            300: "oklch(var(--foreground-300) / <alpha-value>)",
            400: "oklch(var(--foreground-400) / <alpha-value>)",
            500: "oklch(var(--foreground-500) / <alpha-value>)",
            600: "oklch(var(--foreground-600) / <alpha-value>)",
            700: "oklch(var(--foreground-700) / <alpha-value>)",
            800: "oklch(var(--foreground-800) / <alpha-value>)",
            900: "oklch(var(--foreground-900) / <alpha-value>)",
            950: "oklch(var(--foreground-950) / <alpha-value>)",
          },
          brand: {
            blue: "#1A2BFF",
            red: "#FF2A2A",
          },
          cream: {
            DEFAULT: "#F5F0E8",
            50: "#FBF8F3",
            100: "#F5F0E8",
          },
          forest: {
            DEFAULT: "#1A3A2A",
            900: "#0F2419",
          },
          ink: {
            DEFAULT: "#0A0A0A",
            50: "#F5F5F5",
            900: "#0A0A0A",
          },
        },
        fontFamily: {
          sans: ["var(--font-body)", "system-ui", "sans-serif"],
          heading: ["var(--font-heading)", "system-ui", "sans-serif"],
          body: ["var(--font-body)", "system-ui", "sans-serif"],
          label: ["var(--font-label)", "system-ui", "sans-serif"],
          display: ["var(--font-heading)", "system-ui", "sans-serif"],
          serif: ["Instrument Serif", "Georgia", "serif"],
          mono: ["var(--font-mono)", "ui-monospace", "monospace"],
          funnel: ["Funnel Display", "system-ui", "sans-serif"],
        },
      },
    },
    plugins: [],
  }