# Generated by Django 6.1.1 on 2026-09-05 15:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('verification_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('reviews_found', models.IntegerField(default=0)),
                ('reviews_added', models.IntegerField(default=0)),
                ('reviews_updated', models.IntegerField(default=0)),
                ('reviews_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.reviewsource')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_type', models.CharField(choices=[('learner', 'Learner'), ('employer', 'Employer')], max_length=20)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_avatar', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_title', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('programme_studied', models.CharField(blank=True, max_length=255)),
                ('employer_type', models.CharField(blank=True, max_length=255)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('completion_status', models.CharField(blank=True, choices=[('currently-enrolled', 'Currently enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], max_length=30, null=True)),
                ('review_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=30)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('helpful_count', models.IntegerField(default=0)),
                ('external_review_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('response_text', models.TextField(blank=True)),
                ('response_by', models.CharField(blank=True, max_length=255)),
                ('response_role', models.CharField(blank=True, max_length=255)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.company')),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.reviewsource')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.standard')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCategoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ratingcategory')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake', 'Fake'), ('offensive', 'Offensive'), ('personal', 'Personal information'), ('conflict', 'Conflict of interest'), ('spam', 'Spam'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('external_review_id__isnull', False)), fields=('source', 'external_review_id'), name='unique_source_external_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('external_review_id__isnull', True)), fields=('source', 'company', 'content_fingerprint'), name='unique_source_company_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='reviewcategoryrating',
            constraint=models.UniqueConstraint(fields=('review', 'category'), name='unique_review_category_rating'),
        ),
    ]
