# Generated by Django 6.1.1 on 2026-09-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_savedprovider'),
        ('reviews', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pending_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_reviews', to='reviews.companyclaim'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.company'),
        ),
    ]
